language: node_js
node_js:
- '0.12'
- '0.10'
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3
- npm install -g codeclimate-test-reporter
after_install:
- npm run lint
before_script:
- npm run build
script:
- npm run cover
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
matrix:
  fast_finish: true
addons:
  code_climate:
    repo_token:
      secure: O6FOQfZugH9ZFISj4wA7QpufqHna3NpsQ0Z6krugaH0Sou/zNteX5ARkoAWvT2h7YSG26u+U4Ycoxcw/8iiqnj5V7Vhxq0U3RtH/cMMl3T24zekTgFZ21c+CQYsu9Ij8DdqLl1rLbc9t6BrftAq+8CT1bojIFCA48lfspk6BjxSwtjPjsehU6MqYLD5m1I6nuqQss+jGJ9IYYsko6uj+utd/CMY2LrhdHTVJKYqYMg0vawgMjPYYkD1lgSz1YDQGbT9MaHD8sNCuebfEtTucC7XuZikD2LDH1KJ2BV1xbmgMI7er6rzmF4TzBCO2HSedPrZCNWKQFA/83BQu9VdLMibnW2jdp3sxAZ5LoW60QV3Et2GF4n3d5Ko8TdeVroOaKDIIcwiaRCr6UtJqQ6w4sMxMJGWT+8fhzOcdmh72kwCgOVKAjaSkNQ3r51SkFmmrOMJHjxCYWjAF88ENqiHCB+ciQqm8frtS4OvwPS7iA6W3WdmeXwtvuCzTbmavEVoTXjxY4ioeOtwyWRh9ytFZJvXTN4mU6R0TpNLXlo6cYnY6hh4nOLoksdwHvCqOGGRqGDjpiFTBXyJUpKOoiVYqCSak+xi0AbZvRk4GH/BY57sbhPJnHI0CYNEnrtFJwrf6gLmpGq8pLoDF3xWERu0aOc1CnkLdPfBkNDwW9HPoHfM=
notifications:
  slack:
    secure: 3RSMsu5V9qzduxvTYaW5pRxiXW1Jr+jrQ7oYCP7kaeoeyJs8wyzgg2RFU/tAy4y0Pj6LaG70vmQnWVvFdnVD80JyI3WSdNaJvd18gy0TzlP0wgiegSngTg+wGo5e0uMhLU97oJfmnbLOg0tMbkM1dYQlO7u8D/KeXc1Tp2mb/erhdqK1a2GVMELks7llcXq7GS2UIXiqnDQs8f5xxnbTiJXjkg0EblIY0mB9utMMx6Z196minzikylcfX8lMtntAYHM7HYFhIQmkKKrAXv1WhvpQYMWFGAtHE3FhBNEf62e32mYLpVOoaSA8Xvh/M3djPLV/aHPmEKy6qmrm2GxPopFm9RBWQllpJpkM69KlhK+StvUA8bMjV4JOe9LX1GK5mRwo3pH6R/kltWP+D0T4TdO0LPwu18FQbersi/M9+lOSgpkmt4O2aohj7xAmX4nyVio9CAFDjMRVMDEM9dx24wMLSoR0994DWDe9pI1EAzJzeK/TPKszIJoVhapRzIDHv/aP+Jp1mZ0bFWWv62JGtQq5II5nrYfHUaSj4xZQ58PZfYJ1TZfk69PrZdGPVdtAu7GmUjf2gkc4N60LaMV37c4ceYmYlZxu9qcm+y+g0QF3DwN2TXGbWRplakWT4Y+Dfb3hXPg8OUi5IyMwE3WpMuleXDG8R2UUbQPgycMl1VE=
deploy:
  provider: npm
  email: me@boopathi.in
  api_key:
    secure: rFfvy/6F8Q2vLh67sIx+HnbZ+sBkpXbwrGEwpurkgUVtllwDSF4DUMSqzPTUDCywUoMHbgn5NCSuFzXH6p4Wx/Eqcgv+V5bDzCnkOWVY5QW9ZDMwvz90nSb+VLSskEOJYzTGXNm7qpUrXZD6xEFBLxO49OrA5DY/Mw4bhN0IwZcEr5ad4hVdr2EBdHVwtGnvFXmslaf5nRzVh8AdG8bkeWcUmBcGwBW7QiqaTY47a0YPc3UiK9crJhjXbhUlRcKKYX0EgS3/WPxq/AByxXDlwYwgHRn5HcRiaYlpUvWEc7QNNfGGYPTJzA1OYhtXzFqUInPRfMYHjC7DthUX8MTc2Qz8j4kcgZSSfq6Q6nZGMKgO16kXscPXycic1ZlLfYG9KUTTUGeU4umBQyynsvFWbWx9al3hiqm2UpaKNAN8Sax++/RwKCoVcsg4OFjogzM4o9XZM6Y49VtTZm5ZuWMRPiLy249QtGZXzdYBVQfHsXDMVfhHVzEhYKiQEI347+8cevuF468YSnI8jL4ZTLJOCK3pmeTFYz+14xjugd1Cp73iSmIVOoV1Ib9faQlojU88SdmsXD+aJy6AqeKNyftQAyIvphn2VeDdEFTFZHWage7UQzXA+CqFn9E8cgCHDNwE/x9Ag3vHkXYMKj45xQDz92ti5rVP41k1dGlnzTzKR2E=
  on:
    tags: true
    repo: flipkart-incubator/phrontend
