language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3
- npm install -g codeclimate-test-reporter
after_install:
- npm run lint
before_script:
- npm run build
script:
- npm run cover
after_script:
- codeclimate-test-reporter < coverage/lcov.info
matrix:
  fast_finish: true
addons:
  code_climate:
    repo_token:
      secure: O6FOQfZugH9ZFISj4wA7QpufqHna3NpsQ0Z6krugaH0Sou/zNteX5ARkoAWvT2h7YSG26u+U4Ycoxcw/8iiqnj5V7Vhxq0U3RtH/cMMl3T24zekTgFZ21c+CQYsu9Ij8DdqLl1rLbc9t6BrftAq+8CT1bojIFCA48lfspk6BjxSwtjPjsehU6MqYLD5m1I6nuqQss+jGJ9IYYsko6uj+utd/CMY2LrhdHTVJKYqYMg0vawgMjPYYkD1lgSz1YDQGbT9MaHD8sNCuebfEtTucC7XuZikD2LDH1KJ2BV1xbmgMI7er6rzmF4TzBCO2HSedPrZCNWKQFA/83BQu9VdLMibnW2jdp3sxAZ5LoW60QV3Et2GF4n3d5Ko8TdeVroOaKDIIcwiaRCr6UtJqQ6w4sMxMJGWT+8fhzOcdmh72kwCgOVKAjaSkNQ3r51SkFmmrOMJHjxCYWjAF88ENqiHCB+ciQqm8frtS4OvwPS7iA6W3WdmeXwtvuCzTbmavEVoTXjxY4ioeOtwyWRh9ytFZJvXTN4mU6R0TpNLXlo6cYnY6hh4nOLoksdwHvCqOGGRqGDjpiFTBXyJUpKOoiVYqCSak+xi0AbZvRk4GH/BY57sbhPJnHI0CYNEnrtFJwrf6gLmpGq8pLoDF3xWERu0aOc1CnkLdPfBkNDwW9HPoHfM=
notifications:
  slack:
    secure: 3RSMsu5V9qzduxvTYaW5pRxiXW1Jr+jrQ7oYCP7kaeoeyJs8wyzgg2RFU/tAy4y0Pj6LaG70vmQnWVvFdnVD80JyI3WSdNaJvd18gy0TzlP0wgiegSngTg+wGo5e0uMhLU97oJfmnbLOg0tMbkM1dYQlO7u8D/KeXc1Tp2mb/erhdqK1a2GVMELks7llcXq7GS2UIXiqnDQs8f5xxnbTiJXjkg0EblIY0mB9utMMx6Z196minzikylcfX8lMtntAYHM7HYFhIQmkKKrAXv1WhvpQYMWFGAtHE3FhBNEf62e32mYLpVOoaSA8Xvh/M3djPLV/aHPmEKy6qmrm2GxPopFm9RBWQllpJpkM69KlhK+StvUA8bMjV4JOe9LX1GK5mRwo3pH6R/kltWP+D0T4TdO0LPwu18FQbersi/M9+lOSgpkmt4O2aohj7xAmX4nyVio9CAFDjMRVMDEM9dx24wMLSoR0994DWDe9pI1EAzJzeK/TPKszIJoVhapRzIDHv/aP+Jp1mZ0bFWWv62JGtQq5II5nrYfHUaSj4xZQ58PZfYJ1TZfk69PrZdGPVdtAu7GmUjf2gkc4N60LaMV37c4ceYmYlZxu9qcm+y+g0QF3DwN2TXGbWRplakWT4Y+Dfb3hXPg8OUi5IyMwE3WpMuleXDG8R2UUbQPgycMl1VE=
deploy:
  provider: npm
  email: linchpin-dev@flipkart.com
  api_key:
    secure: Cnos1Go6dAR/vg3JpDVBA+NFtL+BojCbGzMEVE+ODCAdEirAcM9Yy8Wppw7u5SJJRdUr7kVHCL60yCTooNS8oyaJyDmnk3kL091YvXURzH8yllrL9FGX9y/u1jSOFYh/8CF8x5G5VdODJBiY4PVk3JTBuhzFgx6xJQlqFNaBor/lweLVsxT2QTOnn4db7MiyDcQDhtIvL8ydgLkqWvVy4X4gqt78wNpKI9aus6Vgz6R1pDa91xyWMhpuIyu8bvK6DeHvifPT77VxDzOV0TyahoVjykD5uNi2tPWEjjQKpfwYFaIWc8WbTvWMQq29LAUK9pYAbEh5RBYUSLEeYk6o12y8ZD3OmXTaFY0N6Zx5D6mvP9D45SZapNyXdUwLL2Rwnm077eNiTCsbUpDy2UTJh3GeO9WMETgLLeeafL2HuVifcqulMPbi7SzHoyjwl+hc5rOaATwacF0T7ijRUdCkB9Y3rgrdkghyMV+ZlvnJAVHUecn+U6wGMYx6QTwhv+8G3ffQ9JEePiAJeqH8iFtYlEkai/PTOrfEqEamPAHvcyPLcdhMl/jPm9DDuESaj5iKU4c81JJsRa1mYUI7dOV6+UyQsvSiK74oLicZhF0FJbyxseepW+5SnqTIHvr9LavubD4FVqDky+p9u1XS2TmsGUSvXawW2Z4H5IVYHs6gSyw=
  on:
    tags: true
    repo: flipkart-incubator/phrontend
